# This is a basic workflow to help you get started with Actions

name: autoCommit

# Controls when the workflow will run
on:
  repository_dispatch:
    types: start-action
  schedule:
    # Runs "at every 5 minutes" (see https://crontab.guru)
    - cron: '0 */5 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cron:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: pull git repository
        uses: actions/checkout@v3

      - name: see dir
        run: ls
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: bash update.sh

      # Runs a set of commands using the runners shell
      - name: see change
        run: cat timestamp.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: bt66
          author_email: bastian.bt66@gmail.com
          message: 'update timestamp'
          add: 'timestamp.txt'
